### ISSUE TITLE
Problems using checkpoint

### ISSUE THREAD

**Issue by Jota-P** [lukas-gandler/OCT-Denoising#2]
Hi, sorry for the disturbance

I am a new uni student and I'm working in a class of image processing and I am doing a task of denoising OCT images. I found this repository and want to try it on my images but I am having some difficulties (noob difficulties probably). Is there anyway you could guide me how to use the pre-trained model on my images?

I thank you in advance.
Take care

**Comment by lukas-gandler** [comment]
Hi!

So the best starting point would be the `src/retouch_denoising.py` script since it has the general workflow of properly loading the trained model and performing the pre-processing steps. However you would have to adjust it since it takes in a whole OCT volume in the mhd format. You would have change line 63 of the script to instead load your image via for example opencv (which is already used in the script).
